name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust branch as needed
  pull_request:
    branches:
      - main  # Adjust branch as needed

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: helloworld-tomcat

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package -X

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        distribution: 'temurin'  # Add the distribution input

    - name: Run Selenium tests
      run: |
        # Add commands to run Selenium tests
           mvn test

  build-and-publish-docker:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        distribution: 'temurin'  # Add the distribution input

    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_NAME }} .

    - name: Publish Docker image
      run: |
        docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.IMAGE_NAME }}:latest
